rm(list=ls())

allopen=c(1,1,1,1)
Sclosed=c(1,1,1,0)
Nclosed=c(1,1,0,1)
Eclosed=c(1,0,1,1)
Wclosed=c(0,1,1,1)
NSclosed=c(1,1,0,0)
ESclosed=c(1,0,1,0)
WSclosed=c(0,1,1,0)
ENclosed=c(1,0,0,1)
WNclosed=c(0,1,0,1)
WEclosed=c(0,0,1,1)
Wopen=c(1,0,0,0)
Eopen=c(0,1,0,0)
Sopen=c(0,0,0,1)
allclosed=c(0,0,0,0)

#top wall          
layout=rbind(WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
for (i in 1:3) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
for (i in 1:3) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
for (i in 1:3) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
for (i in 1:3) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
for (i in 1:3) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
#top rooms
layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
for (i in 1:7) 
{
  layout=rbind(layout,Wclosed)
  for (j in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:3) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:3) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:3) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:3) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:3) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
}
#bottom wall of top rooms
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
# North part of South Wall of North rooms
layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
for (i in 1:4) layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
for (i in 1:4) layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
for (i in 1:4) layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
for (i in 1:4) layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
#North corridor
for (j in 1:1)
{
layout=rbind(layout,Wclosed)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:23) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
}
#North Side of North Wall of Internal space
layout=rbind(layout,Wclosed)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
for (i in 1:3) layout=rbind(layout,Sclosed)
layout=rbind(layout,allopen)
for (i in 1:11) layout=rbind(layout,Sclosed)
layout=rbind(layout,allopen)
for (i in 1:3) layout=rbind(layout,Sclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
#South side of North Wall of Internal Space
for (j in 1:1)
{
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Nclosed)
  for (i in 1:1) layout=rbind(layout,Nclosed)
  layout=rbind(layout,ENclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:4) layout=rbind(layout,Nclosed)
  layout=rbind(layout,ENclosed)
  layout=rbind(layout,WNclosed)
  for (i in 1:5) layout=rbind(layout,Nclosed)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,WNclosed)
  layout=rbind(layout,Nclosed)
  layout=rbind(layout,ENclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
}
#Third Row of Internal Space
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:4) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:5) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
#fourth line of internal area
layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:4) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:5) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
#Fifth line of internal area
for (j in 1:1)
{
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,WSclosed)
  layout=rbind(layout,Sclosed)
  layout=rbind(layout,ESclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:4) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:5) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
}
#Sixth row of internal area
layout=rbind(layout,Wclosed)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,Wclosed)
for (i in 1:4) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:5) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
#Seventh row of internal area
for (j in 1:1)
{
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:4) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:5) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
}

#Eight row of internal area

layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:4) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:5) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)

#Ninth row of internal area

layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:4) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:5) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
#Tenth of internal area
for (j in 1:1)
{
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,WSclosed)
  layout=rbind(layout,Sclosed)
  layout=rbind(layout,ESclosed)
  layout=rbind(layout,WSclosed)
  for (i in 1:4) layout=rbind(layout,Sclosed)
  layout=rbind(layout,ESclosed)
  layout=rbind(layout,WSclosed)
  for (i in 1:5) layout=rbind(layout,Sclosed)
  layout=rbind(layout,ESclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
}
#Eleventh row of internal area
layout=rbind(layout,Wclosed)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
for (i in 1:4) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
for (i in 1:5) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
#Twelveth row of internal area
for (j in 1:1)
{
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:4) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:5) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,WNclosed)
  layout=rbind(layout,Nclosed)
  layout=rbind(layout,ENclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
}
#Thirteenth row of internal area
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:4) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:5) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
#Fourteenth row of internal area
layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:4) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:5) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
#Fourteenth row of internal area
for (j in 1:1)
{
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,WSclosed)
  layout=rbind(layout,Sclosed)
  layout=rbind(layout,ESclosed)
  layout=rbind(layout,WSclosed)
  layout=rbind(layout,Sclosed)
  layout=rbind(layout,Sclosed)
  for (i in 1:2) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:5) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,WNclosed)
  layout=rbind(layout,Nclosed)
  layout=rbind(layout,ENclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
}
#Fifteenth row of internal area
layout=rbind(layout,Wclosed)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WNclosed)
for (i in 1:4) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
for (i in 1:5) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
#Sixteenth row of internal area
for (j in 1:1)
{
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:4) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,Nclosed)
  layout=rbind(layout,Nclosed)
  layout=rbind(layout,Nclosed)
  for (i in 1:5) layout=rbind(layout,Sclosed)
  layout=rbind(layout,ESclosed)
  layout=rbind(layout,WSclosed)
  layout=rbind(layout,Sclosed)
  layout=rbind(layout,Sclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
}
#Seventeenth row of internal area
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:4) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:2) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)

#Eighteenth row of internal area
layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:4) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
for (i in 1:2) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,Wclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)

#Nineteenth row of internal area
for (j in 1:1)
{
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,WSclosed)
  for (i in 1:4) layout=rbind(layout,Sclosed)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,WSclosed)
  for (i in 1:2) layout=rbind(layout,Sclosed)
  layout=rbind(layout,ESclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,Sclosed)
  layout=rbind(layout,ESclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,Sclosed)
  layout=rbind(layout,ESclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,Sclosed)
  layout=rbind(layout,ESclosed)
  layout=rbind(layout,Wclosed)
  layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
}
#South wall of the internal area
layout=rbind(layout,Wclosed)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
for (i in 1:5) layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
for (i in 1:3) layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
for (i in 1:2) layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
for (i in 1:2) layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
for (i in 1:2) layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
layout=rbind(layout,allopen)
for (i in 1:7) layout=rbind(layout,allopen)
layout=rbind(layout,Eclosed)
for (j in 1:1)
{
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:23) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (i in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
}

layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
for (i in 1:23) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)

layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
layout=rbind(layout,Nclosed)
layout=rbind(layout,allopen)
layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
layout=rbind(layout,WNclosed)
for (i in 1:7) layout=rbind(layout,Nclosed)
layout=rbind(layout,ENclosed)
for (i in 1:7) 
{
  layout=rbind(layout,Wclosed)
  for (j in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:3) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:3) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:3) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:3) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:3) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
  layout=rbind(layout,Wclosed)
  for (j in 1:7) layout=rbind(layout,allopen)
  layout=rbind(layout,Eclosed)
}
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)
layout=rbind(layout,WSclosed)
for (i in 1:7) layout=rbind(layout,Sclosed)
layout=rbind(layout,ESclosed)

nodes=rep("outside",9)
nodes=c(nodes,rep("204",5))
nodes=c(nodes,rep("205",5))
nodes=c(nodes,rep("206",5))
nodes=c(nodes,rep("207",5))
nodes=c(nodes,rep("208",5))
nodes=c(nodes,rep("outside",9))
for (i in 1:8)
{
  nodes=c(nodes,rep("outside",9))
  nodes=c(nodes,rep("204",5))
  nodes=c(nodes,rep("205",5))
  nodes=c(nodes,rep("206",5))
  nodes=c(nodes,rep("207",5))
  nodes=c(nodes,rep("208",5))
  nodes=c(nodes,rep("outside",9))
}

nodes=c(nodes,rep("203",9))
nodes=c(nodes,rep("C201",25))
nodes=c(nodes,rep("209",9))
nodes=c(nodes,rep("203",9))
nodes=c(nodes,rep("C201",25))
nodes=c(nodes,rep("209",9))
nodes=c(nodes,rep("203",9))
nodes=c(nodes,rep("C201",25))
nodes=c(nodes,rep("209",9))

nodes=c(nodes,rep("203",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("221",3))
nodes=c(nodes,rep("222",6))
nodes=c(nodes,rep("223",7))
nodes=c(nodes,rep("224",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("209",9))

nodes=c(nodes,rep("203",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("221",3))
nodes=c(nodes,rep("222",6))
nodes=c(nodes,rep("223",7))
nodes=c(nodes,rep("224",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("209",9))

nodes=c(nodes,rep("202",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("221",3))
nodes=c(nodes,rep("222",6))
nodes=c(nodes,rep("223",7))
nodes=c(nodes,rep("225",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("210",9))

nodes=c(nodes,rep("202",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("221",3))
nodes=c(nodes,rep("222",6))
nodes=c(nodes,rep("223",7))
nodes=c(nodes,rep("225",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("210",9))

nodes=c(nodes,rep("202",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("E01",3))
nodes=c(nodes,rep("222",6))
nodes=c(nodes,rep("223",7))
nodes=c(nodes,rep("225",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("210",9))

nodes=c(nodes,rep("202",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("E01",3))
nodes=c(nodes,rep("222",6))
nodes=c(nodes,rep("223",7))
nodes=c(nodes,rep("225",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("210",9))

nodes=c(nodes,rep("202",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("E01",3))
nodes=c(nodes,rep("222",6))
nodes=c(nodes,rep("223",7))
nodes=c(nodes,rep("225",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("210",9))

nodes=c(nodes,rep("201",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("E01",3))
nodes=c(nodes,rep("222",6))
nodes=c(nodes,rep("223",7))
nodes=c(nodes,rep("225",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("211",9))

nodes=c(nodes,rep("201",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("E01",3))
nodes=c(nodes,rep("222",6))
nodes=c(nodes,rep("223",7))
nodes=c(nodes,rep("225",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("211",9))

nodes=c(nodes,rep("201",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("E02",3))
nodes=c(nodes,rep("231",6))
nodes=c(nodes,rep("232",7))
nodes=c(nodes,rep("225",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("211",9))

nodes=c(nodes,rep("201",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("E02",3))
nodes=c(nodes,rep("231",6))
nodes=c(nodes,rep("232",7))
nodes=c(nodes,rep("226",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("211",9))

nodes=c(nodes,rep("201",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("E02",3))
nodes=c(nodes,rep("231",6))
nodes=c(nodes,rep("232",7))
nodes=c(nodes,rep("226",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("211",9))

nodes=c(nodes,rep("220",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("E02",3))
nodes=c(nodes,rep("231",6))
nodes=c(nodes,rep("232",7))
nodes=c(nodes,rep("226",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("212",9))

nodes=c(nodes,rep("220",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("E02",3))
nodes=c(nodes,rep("231",6))
nodes=c(nodes,rep("232",7))
nodes=c(nodes,rep("227",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("212",9))

nodes=c(nodes,rep("220",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("S03",6))
nodes=c(nodes,rep("231",3))
nodes=c(nodes,rep("232",7))
nodes=c(nodes,rep("227",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("212",9))

nodes=c(nodes,rep("220",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("S03",6))
nodes=c(nodes,rep("200",4))
nodes=c(nodes,rep("232",6))
nodes=c(nodes,rep("227",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("212",9))

nodes=c(nodes,rep("220",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("S03",6))
nodes=c(nodes,rep("200",4))
nodes=c(nodes,rep("230",3))
nodes=c(nodes,rep("229",3))
nodes=c(nodes,rep("228",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("212",9))

nodes=c(nodes,rep("219",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("S03",6))
nodes=c(nodes,rep("200",4))
nodes=c(nodes,rep("230",3))
nodes=c(nodes,rep("229",3))
nodes=c(nodes,rep("228",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("213",9))

nodes=c(nodes,rep("219",9))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("S03",6))
nodes=c(nodes,rep("200",4))
nodes=c(nodes,rep("230",3))
nodes=c(nodes,rep("229",3))
nodes=c(nodes,rep("228",3))
nodes=c(nodes,rep("C201",3))
nodes=c(nodes,rep("213",9))

nodes=c(nodes,rep("219",9))
nodes=c(nodes,rep("C201",25))
nodes=c(nodes,rep("213",9))

nodes=c(nodes,rep("219",9))
nodes=c(nodes,rep("C201",25))
nodes=c(nodes,rep("213",9))

nodes=c(nodes,rep("219",9))
nodes=c(nodes,rep("C201",25))
nodes=c(nodes,rep("213",9))

for (i in 1:9)
{
  nodes=c(nodes,rep("outside",9))
  nodes=c(nodes,rep("218",5))
  nodes=c(nodes,rep("217",5))
  nodes=c(nodes,rep("216",5))
  nodes=c(nodes,rep("215",5))
  nodes=c(nodes,rep("214",5))
  nodes=c(nodes,rep("outside",9))
}

layout=cbind(layout,nodes)

write.table(file="layout.csv",sep=",",layout,row.names=FALSE,col.names=FALSE)
